language: java
sudo: false
install: true

service: 
  - docker

jobs:
  include:
    - stage: "Tests"                
      name: "Test"  
      if: branch = master          
      script:        
      - mvn clean verify
      - mvn package -DskipTests             
      - docker build Bdd/. -t $user/pg_devops
      - docker build Httpd/. -t $user/my-running-app
      - docker build sample-application-http-api-server/. -t $user/docker_backend 
      - docker build sample-application-db-changelog-job/. -t $user/db-changelog-job 
      - docker login -u $user -p $psw
      - docker push $user/docker_backend       
      - docker push $user/db-changelog-job 
      - docker push $user/pg_devops
      - docker push $user/my-running-app


cache:
  directories:
  - .autoconf
  - $HOME/.m2