version: '3'
services:
  docker_backend:
    build: ./sample-application-http-api-server/.
    image : fyndir/docker_backend
    networks : 
      - ndevops
    depends_on : 
      - pg_devops
  pg_devops:
    build: ./Bdd/. 
    networks : 
      - ndevops
    image : fyndir/pg_devops
    volumes : 
      - /tmp/data:/var/lib/postgresql/data 
  my-running-app : 
    build : ./Httpd/.
    image : fyndir/my-running-app
    ports : 
      - "80:80"
    networks : 
      - ndevops
  db-changelog-job : 
    build : ./sample-application-db-changelog-job/.
    networks : 
      - ndevops
    image : fyndir/db-changelog-job

networks : 
    ndevops :
  
  
  