version: '3'
services:
  fyndir/docker_backend:
    build: ./sample-application-http-api-server/.
    networks : 
      - ndevops
    depends_on : 
      - pg_devops
  fyndir/pg_devops:
    build: ./Bdd/. 
    networks : 
      - ndevops
    volumes : 
      - /tmp/data:/var/lib/postgresql/data 
  fyndir/my-running-app : 
    build : ./Httpd/.
    ports : 
      - "80:80"
    networks : 
      - ndevops
  fyndir/db-changelog-job : 
    build : ./sample-application-db-changelog-job/.
    networks : 
      - ndevops

networks : 
    ndevops :
  
  
  