version: '3'
services:
  docker_backend:
    build: ./sample-application-http-api-server/.
    container_name : docker_backend
    image : fyndir/docker_backend
    ports : 
      - "8080:8080"
    networks : 
      - ndevops
    depends_on : 
      - pg_devops
  pg_devops:
    container_name: pg_devops
    build: ./Bdd/. 
    networks : 
      - ndevops
    image : fyndir/pg_devops 
  my-running-app :
    container_name : my-running-app
    build : ./Httpd/.
    image : fyndir/my-running-app
    ports : 
      - "80:80"
    networks : 
      - ndevops
    depends_on : 
      - docker_backend
 
networks : 
    ndevops :
  
  
  